puts "Translating switches, variables and common events to English..."

sw_names = [
nil,
'Playing Girl',
'Shadow enabled',
'Slide through events',
'No surf message on colision',
'Common event worked',
'MapConnection Disabled',
'Use real-time clock',
'Disable Time system',
'Pokemon Stored to PSS',
'Tint system enabled',
'It\'s day time',
'It\'s night time',
'It\'s dawn time',
'It\'s evening',
'Use BW inout transition',
'Nuzlocke enabled',
'Riding Acro Bike',
'Prevent FollowMe reset',
'FollowMe enabled',
'Outside / Allowed to fly',
'Allowed to dig',
'Reset follower',
'Riding bike',
'Using strenght',
'MSG : Auto LF',
'Top right choice',
'MSG : No LF on punctuation',
'MSG : Player don\'t look speaking event',
'---Reserved',
'BT Update',
'BT Phase 1',
'BT Phase 2',
'BT Phase 3',
'BT Phase 4',
'BT Phase 5',
'BT Victory',
'BT Defeat',
'BT Caught Pokemon',
'BT Weather -> Map',
'BT Hard exp',
'BT Block flee',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'Healing in Center',
'Player is running',
'Player has running shoes',
'--- ???',
'Flash required',
'Weather = Rain',
'Weather = Sunny',
'Weather = Sandstorm',
'Weather = Snow',
'Weather = Fog',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'Waterfall Skip Altitude check',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'Alpha Pzl solved',
'FollowMe was enabled',
'Using National Dex',
'Pokédex Enabled'
]

var_names = [
nil,
'Trainer ID',
'Nb Seen Pokemon',
'Nb Caught Pokemon',
'Current box in PSS',
'Input number',
'---Reserved',
'---Reserved',
'ID of Trainer to battle',
'--Deprecated set to 0',
'Hour',
'Min',
'Second (unused)',
'Week day',
'Week',
'Month',
'Day',
'Current tone',
'Nb of Human follower',
'Nb of Pk follower',
'Nb of Friend pk follower',
'Current follower',
'Current Pokemon',
'Dig warp ID',
'Dig warp X',
'Dig warp Y',
'TMP 1',
'TMP 2',
'TMP 3',
'TMP 4',
'TMP 5',
'Trainer bt Transition ID',
'Map Transition ID',
'Next Tint transition duration',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'---Reserved',
'Rock Rate',
'Choosen Pokemon',
'Daycare Price',
'Daycare Rate',
'Daycare ID',
'KO warp ID',
'KO warp X',
'KO warp Y',
'Battle mode',
*(['---Reserved'] * 50)
]

ce_names = [
nil,
'Wild battle', 
'Player appearance', 
'Center return', 
'Center Nurse', 
'Speak to follower', 
'Town Map', 
'Quest book', 
'Falling from cracked ground', 
'Enter surf', 
'Leaving surf', 
'Bike', 
'Strenght', 
'Escape rope', 
'Dig', 
'Fly', 
'Daycare (host)', 
'Daycare (eggs)', 
'Berries', 
'Item search / detector', 
'Headbutt', 
'Cut', 
'Old rod', 
'Good Rod', 
'Super Rod', 
'Rock smash', 
'Waterfall', 
'Flash', 
'Whirlpool', 
'Dive', 
'Rock Climb', 
'Teleport', 
'Defog', 
'AcroBike'
]
dest = load_data('Data/System.rxdata')
1.upto(100) do |i|
  dest.switches[i] = sw_names[i]
  dest.variables[i] = var_names[i]
end
save_data(dest, 'Data/System.rxdata')
dest = load_data('Data/CommonEvents.rxdata')
1.upto(ce_names.size - 1) do |i|
  dest[i].name = ce_names[i]
end
save_data(dest, 'Data/CommonEvents.rxdata')
$GAME_LOOP = proc {}
puts "Done..."